-- Land Stack Migration V20: Service Requests Table

CREATE TABLE IF NOT EXISTS service_requests (
    id VARCHAR(50) PRIMARY KEY,
    request_number VARCHAR(50) UNIQUE NOT NULL,
    request_type VARCHAR(50) NOT NULL, -- MUTATION_REQUEST, LAND_RECORD_CORRECTION, OWNERSHIP_UPDATE, BOUNDARY_DISPUTE, FIELD_VERIFICATION, PROPERTY_TAX_REQUEST, REGISTRATION_VERIFICATION, ENCUMBRANCE_VERIFICATION, LAND_USE_CHANGE, AI_RISK_INVESTIGATION, OTHER
    requester_id VARCHAR(100) NOT NULL,
    ulpin VARCHAR(50) REFERENCES parcels(ulpin) ON DELETE CASCADE,
    state_code VARCHAR(10) NOT NULL,
    district_id VARCHAR(50),
    taluka_id VARCHAR(50),
    village_id VARCHAR(50),
    department VARCHAR(50) NOT NULL,
    priority VARCHAR(20) DEFAULT 'NORMAL', -- LOW, NORMAL, HIGH, URGENT
    status VARCHAR(30) DEFAULT 'SUBMITTED', -- SUBMITTED, UNDER_VALIDATION, ASSIGNED, UNDER_REVIEW, FIELD_VERIFICATION_REQUIRED, AWAITING_DOCUMENTS, APPROVED, REJECTED, ESCALATED, COMPLETED, CLOSED
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_req_ulpin ON service_requests(ulpin);
CREATE INDEX IF NOT EXISTS idx_req_status ON service_requests(status);
CREATE INDEX IF NOT EXISTS idx_req_state ON service_requests(state_code);
